### ISSUE TITLE
Running on AIX - whitelist issue

### ISSUE THREAD

**Issue by Crocsmile** [Gorresio/whiteprocess#1]
Hi there, love your work. Just encountered a minor issue, despite declaring some commands like /usr/bin/tail, usr/bin/egrep and /usr/bin/wc in the EXE_ALLOW list they still get killed when running. Any ideas at what I may need to change/look out for?

This is my current setup:
XE_FILTER = yes
ARGS_FILTER = no
AFTER_EXEC_FILTER = no

**Comment by Gorresio** [comment]
Hi, thanks for the feedback
I tried to use **/usr/bin/tail**, **usr/bin/egrep** and **/usr/bin/wc** on a GNU/Linux server in whitelist with real-time output.

The problem I found only with **egrep**, because in my case it is nothing more than an alias of **/bin/grep -E**

Many commands could be aliases or calls/links to other executables (which must be inserted in whitelist).

To avoid problems of this kind, in the next version will be inserted an option that allows you to automatically insert executables in whitelist present in certain directories (ex **/bin/** and **/usr/bin/**).
